#ifdef STM32
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include <neopixelDriver.h>
#include "system.h"
#include "systemClock.h"
#include "uart.h"
#include "consoleHandler.h"
#include "colorInterpolator.h"
#include "interpolators.h"
#include "stringFunctions.h"
#include "taskManager.h"


RGBStream lampsdata[N_LAMPS];
RGBStream * lamps = lampsdata;
uint32_t clr_cnt = 0;
uint32_t bit_cnt = 0;

uint8_t rawdata[N_LAMPS*24+1];
uint8_t* rawdata_ptr = rawdata;

TaskType interpolatorsArray[N_LAMPS];
TasksType interpolators;


volatile uint32_t task;
volatile uint8_t context;

extern CommBufferType usbCommBuffer;
extern CommBufferType btCommBuffer;

/*
 * updates the color along a hue shift with the phase going from 0 to 1535
 * */
void colorUpdate(RGB * color,uint32_t phase)
{
	if (phase < 0x100)
	{
		color->r = 0xFF;
		color->g = phase & 0xFF;
		color->b = 0x00;
	}
	else if (phase < 0x200)
	{
		color->r = 0x1FF - phase;
		color->g = 0xFF;
		color->b = 0x00;
	}
	else if (phase < 0x300)
	{
		color->r = 0x00;
		color->g = 0xFF;
		color->b = phase - 0x200;
	}
	else if (phase < 0x400)
	{
		color->r = 0x00;
		color->g = 0x3FF - phase;
		color->b = 0xFF;
	}
	else if (phase < 0x500)
	{
		color->r = phase - 0x400;
		color->g = 0x00;
		color->b = 0xFF;
	}
	else
	{
		color->r = 0xFF;
		color->g = 0x00;
		color->b = 0x5FF - phase;
	}
}


int main(void)
{
	uint8_t tasksDone = 1;
	ConsoleType usbConsole;
	ConsoleType btConsole;
    setupClock();

    initConsole(&usbConsole);
    initConsole(&btConsole);

	initTimer();
	initUart();
	initBTUart();

	context |= (1 << CONTEXT_USB) | (1 << CONTEXT_BT);
	printf("initializing color interpolators\r\n");

	interpolators.taskArray=(TaskType*)interpolatorsArray;
	interpolators.taskArrayLength=N_LAMPS;
	initInterpolators(&interpolators);


	setLampInterpolator(&interpolators,10,4,MODE_REPEATING); // lamp 10, 4 steps, repeating
	setColorFramesInterpolation(&interpolators, 0,0,0 ,13,INTERPOLATION_LINEAR, 10,0);
	setColorFramesInterpolation(&interpolators, 0,255,0, 5,INTERPOLATION_LINEAR, 10,1);
	setColorFramesInterpolation(&interpolators, 0,45,130, 12,INTERPOLATION_LINEAR, 10,2);
	setColorFramesInterpolation(&interpolators, 200,200,200, 27,INTERPOLATION_LINEAR, 10,3);

	setLampInterpolator(&interpolators,1,2,MODE_REPEATING); // lamp 1, 2 steps, repeating
	setColorFramesInterpolation(&interpolators, 0,0,0 ,50,INTERPOLATION_CONSTANT, 1,0);
	setColorFramesInterpolation(&interpolators, 240,0,0, 50,INTERPOLATION_CONSTANT, 1,1);
	// test hack

	startInterpolators(&interpolators);

	setSendState(SEND_STATE_RTS);


	printf("BallLamp v0.1 running\r\n");

    /* Loop forever */
	for(;;)
	{

		if (getSendState()==SEND_STATE_RTS)//(READY_TO_SEND)
		{
			sendToLed(); // non-blocking, returns long before the neopixel clock pulses have been sent
			tasksDone = 0;
		}

		if ((task & (1 << TASK_USB_CONSOLE))==(1 << TASK_USB_CONSOLE))
		{
			context = (1 << CONTEXT_USB);
			while(usbCommBuffer.inputBufferCnt > 0)
			{
				char* consoleBfr;

				consoleBfr = onCharacterReception(&usbConsole,usbCommBuffer.inputBuffer[usbCommBuffer.inputBufferCnt-1],lamps);
				printf(consoleBfr);
				usbCommBuffer.inputBufferCnt--;
			}
			task &= ~(1 << TASK_USB_CONSOLE);
		}

		if ((task & (1 << TASK_BT_CONSOLE))==(1 << TASK_BT_CONSOLE))
		{
			context = (1 << CONTEXT_BT);
			while(btCommBuffer.inputBufferCnt > 0)
			{
				char* consoleBfr;

				consoleBfr = onCharacterReception(&btConsole,btCommBuffer.inputBuffer[btCommBuffer.inputBufferCnt-1],lamps);
				printf(consoleBfr);
				btCommBuffer.inputBufferCnt--;
			}
			task &= ~(1 << TASK_BT_CONSOLE);
		}
		/*
		 * Time slot for handling tasks
		 */
		if (tasksDone == 0)
		{
			for(uint8_t c=0;c<interpolators.taskArrayLength;c++)
			{
				if ((interpolators.taskArray[c].state & 0x3) != TASK_STATE_STOPPED)
				{
					updateTask(&interpolators.taskArray[c],lamps);
				}
			}
			tasksDone=1;
		}

		// if the tasks are finished after the fps time has elapsed the next frame doesn't show
		// the correct data due to a buffer underrun
		if(getSendState()==SEND_STATE_BUFFER_UNDERRUN)
		{
			// potential error handling
			context |= (1 << CONTEXT_USB) | (1 << CONTEXT_BT);
			printf("BufferUnderrun!!\r\n");
		}

		if (getSendState()==SEND_STATE_SENT || getSendState()==SEND_STATE_BUFFER_UNDERRUN)// is in wait state after after the data transfer
		{
			decompressRgbArray(lamps,N_LAMPS);
		}

		sendCharAsyncUsb();
		sendCharAsyncBt();

	}
}
#endif
